# Generated by Django 6.0 on 2026-01-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion & Apparel', 'Fashion & Apparel'), ('Home & Kitchen', 'Home & Kitchen'), ('Home & Kitchen', 'Home & Kitchen'), ('Toys & Games', 'Toys & Games'), ('Beauty & Personal Care', 'Beauty & Personal Care'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Books & Media', 'Books & Media'), ('Grocery & Essentials', 'Grocery & Essentials'), ('Automotive', 'Automotive'), ('Misc / Other', 'Misc / Other')], max_length=100),
        ),
    ]
