# Generated by Django 6.0 on 2026-01-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion & fpparel', 'Fashion & Apparel'), ('home & kitchen', 'Home & Kitchen'), ('toys & games', 'Toys & Games'), ('beauty & personal care', 'Beauty & Personal Care'), ('sports & outdoors', 'Sports & Outdoors'), ('books & media', 'Books & Media'), ('grocery & essentials', 'Grocery & Essentials'), ('automotive', 'Automotive'), ('misc/other', 'Misc / Other')], max_length=100),
        ),
    ]
