# Generated by Django 6.0 on 2026-01-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_buyer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_seller',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Seller', 'Seller')], max_length=20, null=True),
        ),
    ]
