# Generated by Django 6.0 on 2026-01-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_is_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('buyer', 'buyer'), ('Seller', 'Seller')], max_length=20, null=True),
        ),
    ]
