# Generated by Django 6.0 on 2026-01-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_img',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='uunn', upload_to='users/'),
        ),
    ]
